// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNz0BjXopLE1VW1wmtX4BHqNYy88tX7EU',
    appId: '1:131566717398:web:c013efece5f6c12f5f3c77',
    messagingSenderId: '131566717398',
    projectId: 'noteapp-41dcb',
    authDomain: 'noteapp-41dcb.firebaseapp.com',
    storageBucket: 'noteapp-41dcb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPeWwbeoD6oLT_nhXj3JUMZ_YNBjBrmY',
    appId: '1:131566717398:android:9c791d63584f245f5f3c77',
    messagingSenderId: '131566717398',
    projectId: 'noteapp-41dcb',
    storageBucket: 'noteapp-41dcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6kM7lXuxb9fPujvxLUjtAx9OHqkMF9Bs',
    appId: '1:131566717398:ios:8a38d0196ec59aef5f3c77',
    messagingSenderId: '131566717398',
    projectId: 'noteapp-41dcb',
    storageBucket: 'noteapp-41dcb.appspot.com',
    iosClientId: '131566717398-sltrr003eeak3qb9l7qdisiq8mn6qsjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6kM7lXuxb9fPujvxLUjtAx9OHqkMF9Bs',
    appId: '1:131566717398:ios:8a38d0196ec59aef5f3c77',
    messagingSenderId: '131566717398',
    projectId: 'noteapp-41dcb',
    storageBucket: 'noteapp-41dcb.appspot.com',
    iosClientId: '131566717398-sltrr003eeak3qb9l7qdisiq8mn6qsjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
